[common_basic]
enable_rule_generator=false
overwrite_original_rules=true
log_level=error
rule_providers=false

[custom]
# حفظ کامل ایموجی‌ها (🟢🔴⚡✅)
rename_node=^(.*)$=$1=
flag_rename=false
emoji_rename=false
append_rename=false
hide_node=false

ruleset=DIRECT,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/ir-lite.txt
ruleset=REJECT,https://raw.githubusercontent.com/Chocolate4U/Iran-clash-rules/release/malware.txt
ruleset=✅Select,[]FINAL

custom_proxy_group=✅Select`select`[]♻️Auto`.*`DIRECT  
custom_proxy_group=♻️Auto`url-test`.*`http://www.gstatic.com/generate_204`300,,50
